/*
 * generated by Xtext
 */
package org.uqbar;

import org.eclipse.xtext.xbase.compiler.XbaseCompiler;
import org.eclipse.xtext.xbase.typesystem.computation.ITypeComputer;
import org.eclipse.xtext.xbase.typesystem.computation.XbaseTypeComputer;
import org.eclipse.xtext.xbase.typing.ITypeProvider;

/**
 * Use this class to register components to be used at runtime / without the
 * Equinox extension registry.
 */
public class HoopeRuntimeModule extends org.uqbar.AbstractHoopeRuntimeModule {
	public Class<? extends ITypeProvider> bindITypeProvider() {
		return HoopeTypeProvider.class;
	}

	public Class<? extends XbaseCompiler> bindXbaseCompiler() {
		return HoopeCompiler.class;
	}
	/*
	public Class<? extends XbaseTypeComputer> bindXBaseComputer() {
		return HoopeTypeComputer.class;
	}
	 */

	public Class<? extends ITypeComputer> bindITypeComputer() {
		return HoopeTypeComputer.class;
	}
}
