/*
 * generated by Xtext
 */
package org.uqbar.ui.contentassist

import org.uqbar.ui.contentassist.AbstractHoopeProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class HoopeProposalProvider extends AbstractHoopeProposalProvider {
}
