/*
 * generated by Xtext
 */
package org.uqbar.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.uqbar.ui.internal.HoopeActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class HoopeExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return HoopeActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return HoopeActivator.getInstance().getInjector(HoopeActivator.ORG_UQBAR_HOOPE);
	}
	
}
