/*
* generated by Xtext
*/
package org.uqbar.hoope.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class HOOPLAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/uqbar/hoope/parser/antlr/internal/InternalHOOPL.tokens");
	}
}
