/*
 * generated by Xtext
 */
package org.uqbar.hoope.ui.contentassist

import org.uqbar.hoope.ui.contentassist.AbstractHOOPLProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
class HOOPLProposalProvider extends AbstractHOOPLProposalProvider {
}
