/*
* generated by Xtext
*/
package org.uqbar.hoope;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class HOOPLUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.uqbar.hoope.ui.internal.HOOPLActivator.getInstance().getInjector("org.uqbar.hoope.HOOPL");
	}
	
}
