/*
 	* generated by Xtext
 */
package org.uqbar.hoope.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class HOOPLUiModule extends org.uqbar.hoope.ui.AbstractHOOPLUiModule {
	public HOOPLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
