/*
 * generated by Xtext
 */
package org.uqbar.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class HoopeUiModule extends org.uqbar.ui.AbstractHoopeUiModule {
	public HoopeUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
