/*
* generated by Xtext
*/
package org.uqbar.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.uqbar.services.HoopeGrammarAccess;

public class HoopeParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private HoopeGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.uqbar.parser.antlr.internal.InternalHoopeParser createParser(XtextTokenStream stream) {
		return new org.uqbar.parser.antlr.internal.InternalHoopeParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Program";
	}
	
	public HoopeGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(HoopeGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
