/*
* generated by Xtext
*/
package org.uqbar;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class HoopeUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.uqbar.ui.internal.HoopeActivator.getInstance().getInjector("org.uqbar.Hoope");
	}
	
}
