/**
 * generated by Xtext
 */
package org.uqbar.hoope.validation;

import org.uqbar.hoope.validation.AbstractHOOPLValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class HOOPLValidator extends AbstractHOOPLValidator {
}
