/*
* generated by Xtext
*/
package org.uqbar.hoope;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class HOOPLStandaloneSetup extends HOOPLStandaloneSetupGenerated{

	public static void doSetup() {
		new HOOPLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

